In [2]:
import numpy as np
from sklearn import preprocessing
import os
os.chdir("C:\\Users\HP\Downloads")

In [3]:
data=np.genfromtxt("0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
data1=np.genfromtxt("0000000000002419_test_ccpp_x_test (1).csv",delimiter=",")
x_train=data[:,0:4]
print(x_train.shape)
x_train

(7176, 4)


array([[   8.58,   38.38, 1021.03,   84.37],
       [  21.79,   58.2 , 1017.21,   66.74],
       [  16.64,   48.92, 1011.55,   78.76],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74],
       [  16.37,   54.3 , 1017.94,   63.63],
       [  30.11,   62.04, 1010.69,   47.96]])

In [3]:
data=np.genfromtxt("0000000000002419_training_ccpp_x_y_train.csv",delimiter=",")
data1=np.genfromtxt("0000000000002419_test_ccpp_x_test (1).csv",delimiter=",")
data.shape,data1.shape
x_train=data[:,0:4]
y_train=data[:,4]
data.shape,data1.shape
x_train=np.insert(x_train,4,1,axis=1)
print(x_train.shape)
x_test=data1[:,:]
x_test.shape

(7176, 5)


(2392, 4)

In [4]:
x1=data[:,1:3]
min_max_scaler=preprocessing.MinMaxScaler(feature_range=(40,100))
x1_min_max_scaler=min_max_scaler.fit_transform(x1)
print(x1_min_max_scaler)

[[53.90035587 81.78173719]
 [75.06049822 76.10987379]
 [65.15302491 67.70601336]
 ...
 [86.95373665 64.45434298]
 [70.89679715 77.19376392]
 [79.16014235 66.42910171]]


In [5]:
def step_gradient(x_train,learning_rate,m):
    M=len(x_train)
    m_slope=0
    for i in range(M):
        x=x_train[i,:]
        y=y_train[i]
        m_slope+=(-2/M)*(y-(m*x).sum())*x
    m=m-learning_rate*m_slope   
    return m    

In [6]:
def gd(x_train,learning_rate,num_iteration):
    m=np.zeros(5)
    for i in range(num_iteration):
        m=step_gradient(x_train,learning_rate,m)
        
    return m    

In [7]:
x_test=np.insert(x_test,4,1,axis=1)
learning_rate=0.0000001
num_iteration=1500000
m=gd(x_train,learning_rate,num_iteration)

In [8]:
def predict(x_test,m):
    M=len(x_test)
    y=np.zeros(M)
    for i in range(M):
        x=x_test[i,:]
        y[i]=(x*m).sum()
    return y
predict(x_test,m)
np.savetxt("project.csv",predict(x_test,m))
predict(x_test,m)

array([471.11362051, 470.41954583, 432.08158843, ..., 439.495319  ,
       452.75480776, 450.99436752])